### ISSUE TITLE
Get response from safaricom after a successful payment 

### ISSUE THREAD

**Issue by AustineGwa** [AustineGwa/DarajaApiTestApp#5]
get the response from  safaricom via the callback url  and persist it to the apps storage for future refference

**Comment by AustineGwa** [comment]
Done Created a php file (mpesa-callbackurl.php)that listens for this response and logs a Json

**Comment by Talamproxy** [comment]
please help, am new to daraja. how do i configure this include 'lib/class.connect.php';
